# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "SunoBTSpring"
product_name = "SunoBTSpring"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Suno"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_02", "P1_07", "P0_31", "P0_29","P0_02"]
output_pins = ["P0_10", "P0_09","P0_06","P0_08","P0_17","P1_15","P1_13","P1_11","P0_20","P0_22","P0_24","P1_00","P0_11", "P1_04","P1_06"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        ["A", "B", "C"],
        ["Kc1", "Kc2", "Kc3"],
        ["LCtrl", "MO(1)", "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"]
    ],
    [
        ["_", "TT(1)", "TG(2)"],
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"]
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
