# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "SunoBTSpring"
product_name = "SunoBTSpring"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Suno"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_02", "P1_07", "P0_31", "P0_29","P0_02"]
output_pins = ["P0_10", "P0_09","P0_06","P0_08","P0_17","P1_15","P1_13","P1_11","P0_20","P0_22","P0_24","P1_00","P0_11", "P1_04","P1_06"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 5
cols = 15
layers = 4
keymap = [
    [
        ["Escape", "Grave", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus", "Equal", "Backspace"],
        ["TG(2)", "Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LeftBracket", "RightBracket", "Backslash"],
        ["MO(3)", "LCtrl", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "Enter", "_"],
        ["LShift", "Z", "X", "C", "V", "B", "B", "N", "M", "Comma", "Dot", "Slash", "UP", "RShift", "_"],
        ["LCtrl", "LGui", "LAlt", "_", "LT(2,Space)", "Space", "_", "_", "_", "MO(1)", "_", "Left", "Down", "Right", "_"]
    ],
    [
        ["_", "No", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "Delete"],
        ["_", "_", "No", "No", "No", "No", "No", "No", "PageUp", "Insert", "No", "PrintScreen", "No", "No", "No"],
        ["_", "CapsLock", "AudioVolDown", "AudioVolUp", "AudioMute", "No", "No", "Home", "PageDown", "No", "No", "No", "No", "_", "_"],
        ["_", "No", "No", "No", "No", "No", "No", "End", "No", "No", "No", "No", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    [
        ["_", "No", "No", "No", "No", "No", "No", "No", "No", "KpAsterisk", "No", "No", "KpMinus", "KpPlus", "Backspace"],
        ["_", "_", "No", "No", "No", "No", "No", "Kp7", "Kp8", "Kp9", "No", "No", "No", "No", "KpSlash"],
        ["_", "CapsLock", "No", "NumLock", "No", "No", "No", "Kp4", "Kp5", "Kp6", "No", "No", "No", "KpEqual", "_"],
        ["_", "No", "No", "Calculator", "No", "No", "Kp1", "Kp2", "Kp3", "No", "No", "No", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "Kp0", "_", "_", "_", "KpDot", "_", "_", "_", "_", "_"]
    ],
    [
        ["_", "No", "MouseAccel0", "MouseAccel1", "MouseAccel2", "No", "No", "No", "No", "No", "No", "No", "No", "No", "Delete"],
        ["_", "_", "No", "MouseWheelUp", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["_", "CapsLock", "MouseWheelLeft", "MouseWheelRight", "No", "No", "No", "No", "No", "No", "No", "No", "No", "_", "_"],
        ["_", "MouseWheelDown", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "MouseUp", "No", "_"],
        ["_", "_", "_", "_", "MouseBtn1", "MouseBtn2", "_", "_", "_", "_", "_", "MouseLeft", "MouseDown", "MouseRight", "_"]
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock.pin = "P1_01"
capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"
